export enum CarreraBaseBis {
    //TECNICATURAS
    ADMINISTRACION = 'ADMINISTRACION',
    ENOLOGIA = 'ENOLOGIA',
    PROCEDIMIENTOS_TECNOLOGIAS_AMBIENTALES = 'PROCEDIMIENTOS_TECNOLOGIAS_AMBIENTALES',
    PRODUCCION_TEXTIL = 'PRODUCCION_TEXTIL',
    PROGRAMACION = 'PROGRAMACION',
    //INGENIERIAS
    INGENIERIA_NAVAL = 'INGENIERIA_NAVAL',
    INGENIERIA_PESQUERA = 'INGENIERIA_PESQUERA'
}
