export enum TipoDocumento {
    DNI = 'DNI',
    RECIBO_SUELDO = 'RECIBO_SUELDO',
    CERTIFICADO_ALUMNO_REGULAR = 'CERTIFICADO_ALUMNO_REGULAR',
    CERTIFICADO_CONDICION_SALUD = 'CERTIFICADO_CONDICION_SALUD',
    ANALITICO = 'ANALITICO',
    OTRO = 'OTRO',
    NOTA_AVAL_DIRECTOR = 'NOTA_AVAL_DIRECTOR',
    CARTA_MOTIVACION = 'CARTA_MOTIVACION',
    CERTIFICADO_MEDICO = 'CERTIFICADO_MEDICO',
    INFORME_FINAL = 'INFORME_FINAL',
    FORMULARIO_INSCRIPCION = 'FORMULARIO_INSCRIPCION',
    CURRICULUM_VITAE = 'CURRICULUM_VITAE'
}
