package com.UTN_BECAS.Sistema_Becas.Archivos.Model;

public enum TipoArchivo {
    DNI,
    RECIBO_SUELDO,
    CERTIFICADO_ALUMNO_REGULAR,
    CERTIFICADO_CONDICION_SALUD,
    ANALITICO,
    OTRO,
    NOTA_AVAL_DIRECTOR,
    CARTA_MOTIVACION,
    CERTIFICADO_MEDICO,
    INFORME_FINAL
}
