package com.UTN_BECAS.Sistema_Becas.Postulaciones.Enums;

public enum CarreraBaseBis {
    //TECNICATURAS
    ADMINISTRACION,
    ENOLOGIA,
    PROCEDIMIENTOS_TECNOLOGIAS_AMBIENTALES,
    PRODUCCION_TEXTIL,
    PROGRAMACION,
    //INGENIERIAS
    INGENIERIA_NAVAL,
    INGENIERIA_PESQUERA
}
